import { Inter } from "next/font/google";
import "./globals.css";
import NavBarDes from "./components/navBar/navBarDes";
import FooterDes from "./components/footer/footerDes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#F7FBFE]`} >
        <NavBarDes />
        {children}
        <FooterDes />
      </body>
    </html>
  );
}
