import { Inter } from "next/font/google";
import "./globals.css";
import NavBarDes from "./components/navBar/navBarDes";
import FooterDes from "./components/footer/footerDes";
import NavBarMob from "./components/navBar/navBarMob";
import Checkuser from "./components/user";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#F7FBFE]`} >
        <div className="max-md:hidden"> <NavBarDes /></div>
        <div className="md:hidden"> <NavBarMob /> </div>

        {children}
        <FooterDes />

      </body>
    </html>
  );
}
